"""Built-in catalogue of LLMSpec entries keyed by model name."""

from kavier_library.specs.LLMSpec import LLMSpec

#: Mapping of model name -> LLMSpec; look up via ``get_llm``.
LLM_SPEC_LIBRARY = {
    "Llama-3-8B": LLMSpec(
        llm_name="Llama-3-8B",
        n_layers=32,
        n_heads=32,
        d_head=128,
        d_model=4096,
        p_bytes=2,
        m_params=8e9,
    ),
    "Llama-2-13B": LLMSpec(
        llm_name="Llama-2-13B",
        n_layers=40,
        n_heads=40,
        d_head=128,
        d_model=5120,
        p_bytes=2,
        m_params=13e9,
    ),
    "Granite-20B": LLMSpec(
        llm_name="Granite-20B",
        n_layers=52,
        n_heads=48,
        d_head=128,
        d_model=6144,
        p_bytes=2,
        m_params=20e9,
    ),
    "MPT-30B": LLMSpec(
        llm_name="MPT-30B",
        n_layers=48,
        n_heads=64,
        d_head=112,
        d_model=7168,
        p_bytes=2,
        m_params=30e9,
    ),
    "OPT-30B": LLMSpec(
        llm_name="OPT-30B",
        n_layers=48,
        n_heads=56,
        d_head=128,
        d_model=7168,
        p_bytes=2,
        m_params=30e9,
    ),
    "OPT-175B": LLMSpec(
        llm_name="OPT-175B",
        n_layers=96,
        n_heads=96,
        d_head=128,
        d_model=12288,
        p_bytes=2,
        m_params=175e9,
    ),
    "BLOOM-176B": LLMSpec(
        llm_name="BLOOM-176B",
        n_layers=70,
        n_heads=112,
        d_head=128,
        d_model=14336,
        p_bytes=2,
        m_params=176e9,
    ),
    "llama3.1-70b": LLMSpec(
        llm_name="llama3.1-70b",
        n_layers=80,
        n_heads=64,
        d_head=128,
        d_model=8192,
        p_bytes=2,
        m_params=70e9,
    ),
    "granite-3.1-3b-a800m-instruct": LLMSpec(
        llm_name="granite-3.1-3b-a800m-instruct",
        n_layers=32,
        n_heads=24,
        d_head=64,
        d_model=1536,
        p_bytes=2,
        m_params=3.3e9,
        active_params=800e6,
    ),
    "mistral-7b-v0.1": LLMSpec(
        llm_name="mistral-7b-v0.1",
        n_layers=32,
        n_heads=32,
        d_head=128,
        d_model=4096,
        p_bytes=2,
        m_params=7e9,
    ),
    "mixtral-8x7b-instruct-v0.1": LLMSpec(
        llm_name="mixtral-8x7b-instruct-v0.1",
        n_layers=32,
        n_heads=32,
        d_head=128,
        d_model=4096,
        p_bytes=2,
        m_params=47e9,
        active_params=13e9,
    ),
    "granite-3.3-8b": LLMSpec(
        llm_name="granite-3.3-8b",
        n_layers=40,
        n_heads=32,
        d_head=128,
        d_model=4096,
        p_bytes=2,
        m_params=8e9,
    ),
    # --- dense models added for the 4-model comparison set (specs from HF configs) ---
    "llama3.2-3b": LLMSpec(
        llm_name="llama3.2-3b",
        n_layers=28,
        n_heads=24,
        d_head=128,
        d_model=3072,
        p_bytes=2,
        m_params=3.21e9,
    ),
    "granite-3-8b": LLMSpec(
        llm_name="granite-3-8b",
        n_layers=40,
        n_heads=32,
        d_head=128,
        d_model=4096,
        p_bytes=2,
        m_params=8.1e9,
    ),
    # --- in-vitro (rwt3-llmbuild) models added for the real-trace cluster run ---
    # granite-3.1-8b shares the granite-3.0-8b architecture (HF config: 4096 d_model,
    # 40 layers, 32 heads, head_dim 128, ~8.1B params); calibrated on its own PD1 rows.
    "granite-3.1-8b-instruct": LLMSpec(
        llm_name="granite-3.1-8b-instruct",
        n_layers=40,
        n_heads=32,
        d_head=128,
        d_model=4096,
        p_bytes=2,
        m_params=8.1e9,
    ),
    # granite-3.1-2b HF config: 2048 d_model, 40 layers, 32 heads, 8 KV heads (GQA),
    # head_dim 64, ffn 8192, vocab 49152 -> ~2.53B params (tied embeddings).
    "granite-3.1-2b": LLMSpec(
        llm_name="granite-3.1-2b",
        n_layers=40,
        n_heads=32,
        d_head=64,
        d_model=2048,
        p_bytes=2,
        m_params=2.53e9,
    ),
}
