name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[dev]
      - name: Ruff auto-fix
        run: |
          ruff check . --fix
          ruff format .
      - name: Ruff (lint + format check)
        run: |
          # Fail if there are any lint errors
          ruff check .

      - name: Mypy (type check)
        run: |
          mypy --show-error-codes .

  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-py${{ matrix.python-version }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-py${{ matrix.python-version }}-

      - name: Install project + dev deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev]

      - name: Run pytest
        run: pytest -q
